const express = require('express');
const router = express.Router();
const authRoutes = require('./auth.routes');
const userRoutes = require('./user.routes');
const printingRoutes = require('./printing.routes');
const adminRoutes = require('./admin.routes');
const ceoRoutes = require('./ceo.routes');
const customerRoutes = require('./customer.routes');
const financeRoutes = require('./finance.routes');
const inventoryRoutes = require('./inventory.routes');
const posRoutes = require('./pos.routes');
const purchaseRoutes = require('./purchase.routes');
const reportRoutes = require('./report.routes');
const carRoutes = require('./car.routes');
const rentalOrderRoutes = require('./rentalOrder.routes');
const notificationRoutes = require('./notification.routes');
const pharmacyRoutes = require('./pharmacy.routes');
const farmingRoutes = require('./farming.routes');
const retailRoutes = require('./retail.routes');
const galleryRoutes = require('./gallery.routes');
const publicRoutes = require('./public.routes');
const newsRoutes = require('./news.routes');
const tenderRoutes = require('./tender.routes');
const contactRoutes = require('./contact.routes');
const hrRoutes = require('./hr.routes');
const storeRoutes = require('./store.routes');

router.use('/auth', authRoutes);
router.use('/users', userRoutes);
router.use('/printing', printingRoutes);
router.use('/admin', adminRoutes);
router.use('/ceo', ceoRoutes);
router.use('/customer', customerRoutes);
router.use('/finance', financeRoutes);
router.use('/inventory', inventoryRoutes);
router.use('/pos', posRoutes);
router.use('/purchase', purchaseRoutes);
router.use('/reports', reportRoutes);
router.use('/cars', carRoutes);
router.use('/rental-orders', rentalOrderRoutes);
router.use('/notifications', notificationRoutes);
router.use('/pharmacy', pharmacyRoutes);
router.use('/farming', farmingRoutes);
router.use('/retail', retailRoutes);
router.use('/gallery', galleryRoutes);
router.use('/public', publicRoutes);
router.use('/news', newsRoutes);
router.use('/tenders', tenderRoutes);
router.use('/contact', contactRoutes);
router.use('/hr', hrRoutes);
router.use('/store', storeRoutes);

module.exports = router;
