const express = require('express');
const router = express.Router();
const authRoutes = require('./auth.routes');
const userRoutes = require('./user.routes');
const printingRoutes = require('./printing.routes');
const adminRoutes = require('./admin.routes');
const ceoRoutes = require('./ceo.routes');
const customerRoutes = require('./customer.routes');
const financeRoutes = require('./finance.routes');
const inventoryRoutes = require('./inventory.routes');
const posRoutes = require('./pos.routes');
const purchaseRoutes = require('./purchase.routes');
const reportRoutes = require('./report.routes');
const carRoutes = require('./car.routes');
const rentalOrderRoutes = require('./rentalOrder.routes');
const notificationRoutes = require('./notification.routes');

router.use('/auth', authRoutes);
router.use('/users', userRoutes);
router.use('/printing', printingRoutes);
router.use('/admin', adminRoutes);
router.use('/ceo', ceoRoutes);
router.use('/customer', customerRoutes);
router.use('/finance', financeRoutes);
router.use('/inventory', inventoryRoutes);
router.use('/pos', posRoutes);
router.use('/purchase', purchaseRoutes);
router.use('/reports', reportRoutes);
router.use('/cars', carRoutes);
router.use('/rental-orders', rentalOrderRoutes);
router.use('/notifications', notificationRoutes);

module.exports = router;
